baseURL = 'https://lennartalff.net'
languageCode = 'en-us'
title = 'Thies Lennart Alff'
theme = 'hugo-coder'
defaultContentLanguage = 'en'
pygmentsStyle = 'bw'
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
lastmod = ['lastmod', ':git', 'date', 'publishDate']
publishDate = ['publishDate', 'date']

[params]
author = 'Thies Lennart Alff'
colorScheme = 'auto'
hideColorSchemeToggle = false
dateFormat = '02.01. 2006'
avatarURL = 'images/avatar.jpg'

[taxonomies]
category = 'categories'
series = 'series'
tag = 'tags'
author = 'authors'

[[params.social]]
name = 'GitHub'
icon = 'fa fa-2x fa-github'
weight = 1
url = 'https://github.com/lennartalff/'

[[params.social]]
name = 'GitLab'
icon = 'fa fa-2x fa-gitlab'
weight = 1
url = 'https://gitlab.com/lennartalff/'

[[menu.main]]
name = 'Recipes'
weight = 3
url = 'recipes/'

[[menu.main]]
name = 'Cycling'
weight = 2
url = 'cycling/'

[[menu.main]]
name = 'Posts'
weight = 1
url = 'posts/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
